sudo: required

language: python

services:
  - docker

before_install:
  - echo "MYSQL_DATABASE=proto_db MYSQL_ALLOW_EMPTY_PASSWORD=yes" > server/.env
  - sudo /etc/init.d/mysql stop
  - docker-compose -f server/docker-compose.yml up -d

script:
  - docker exec server ./manage.py test
